### PR TITLE
fix:#39

### PR DESCRIPTION
**Pull request by DreamMaoMao**
fix:(#39 )

### CODE REVIEW

**Comment by crusj** [comment]
I changed some code which caused the conflict, but should be able to fix the bug.

**Comment by DreamMaoMao** [comment]
I just updated your commit and it doesn't seem to be working properly.

image

E5108: Error executing lua: ...al/share/nvim/lazy/bookmarks.nvim/lua/bookmarks/list.lua:288: Cursor position outside buffer

stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...al/share/nvim/lazy/bookmarks.nvim/lua/bookmarks/list.lua:288: in function 'jump'
	.../.local/share/nvim/lazy/bookmarks.nvim/lua/bookmarks.lua:57: in function <.../.local/share/nvim/lazy/bookmarks.nvim/lua/bookmarks.lua:56>

**Comment by DreamMaoMao** [comment]
Not only that,the jump location is all wrong. and can't delete mark.

https://github.com/crusj/bookmarks.nvim/assets/30348075/e0287548-86e7-47ea-8c7a-70cf42975894

**Comment by crusj** [comment]
> I just updated your commit and it doesn't seem to be working properly.
> 
> image
> 
> E5108: Error executing lua: ...al/share/nvim/lazy/bookmarks.nvim/lua/bookmarks/list.lua:288: Cursor position outside buffer
> 
> stack traceback: [C]: in function 'nvim_win_set_cursor' ...al/share/nvim/lazy/bookmarks.nvim/lua/bookmarks/list.lua:288: in function 'jump' .../.local/share/nvim/lazy/bookmarks.nvim/lua/bookmarks.lua:57: in function <.../.local/share/nvim/lazy/bookmarks.nvim/lua/bookmarks.lua:56>

Fix it.

**Comment by DreamMaoMao** [comment]
The problem of line jump error still exists, he will jump to the first line of the file, rather than the previously marked line


https://github.com/crusj/bookmarks.nvim/assets/30348075/80b3e99a-6cb3-4ea8-bab5-86df8d62e7f6

**Comment by DreamMaoMao** [comment]
There's only a small chance the jump is right

**Comment by crusj** [comment]
> The problem of line jump error still exists, he will jump to the first line of the file, rather than the previously marked line
> 
>  2024-01-02.14-15-21.mp4

🤣

**Comment by crusj** [comment]
> There's only a small chance the jump is right



> There's only a small chance the jump is right

It always succes in my pc.

**Comment by DreamMaoMao** [comment]
Sad stories, always jump to the first line here


https://github.com/crusj/bookmarks.nvim/assets/30348075/4e6ac39d-8296-4e27-ac38-4b7c1933ea24

**Pull request merged**
